# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/auth
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/blocks
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/graph
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/kafka-consumer
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/kafka-event-consumer
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/merminator
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/mongo-connector
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/mongo-event-builder
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/payload-generator
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/payload-validator
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/server
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/url
    schedule:
      interval: daily
