/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerConfig {
  port: number;
  graphlettes: {
    path: string;
    mongo: MongoConfig;
    schema: string;
    dtoConfig: DTOConfiguration;
    [k: string]: unknown;
  }[];
}
export interface MongoConfig {
  uri: string;
  collection: string;
  db: string;
  [k: string]: unknown;
}
export interface DTOConfiguration {
  resolvers?: {
    [k: string]: DependencyResolver;
  };
  singletons?: {
    [k: string]: QueryResolver;
  };
  scalars?: {
    [k: string]: QueryResolver;
  };
  additionalProperties?: false;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Z0-9._%+-]+$".
 */
export interface DependencyResolver {
  id?: string;
  url: string;
  queryName: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Z0-9._%+-]+$".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Z0-9._%+-]+$".
 */
export interface QueryResolver {
  id?: string;
  query: string;
}
