/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DTOConfiguration {
  resolvers?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Z0-9._%+-]+$".
     */
    [k: string]: {
      id?: string;
      url: string;
      queryName: string;
    };
  };
  singletons?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Z0-9._%+-]+$".
     */
    [k: string]: {
      id?: string;
      query: string;
    };
  };
  additionalProperties?: false;
  [k: string]: unknown;
}
